const MEDIA_STREAM_TYPES = {
  MP4: 'MP4',
  WEBM: 'WEBM',
  HLS: 'HLS',
  DASH: 'DASH',
};

const MEDIA_STREAM_DELIVERY_TYPE: any = {};

MEDIA_STREAM_DELIVERY_TYPE[MEDIA_STREAM_DELIVERY_TYPE.NATIVE_PROGRESSIVE = 0] = 'NATIVE_PROGRESSIVE';
MEDIA_STREAM_DELIVERY_TYPE[MEDIA_STREAM_DELIVERY_TYPE.ADAPTIVE_VIA_MSE = 1] = 'ADAPTIVE_VIA_MSE';
MEDIA_STREAM_DELIVERY_TYPE[MEDIA_STREAM_DELIVERY_TYPE.NATIVE_ADAPTIVE = 2] = 'NATIVE_ADAPTIVE';

export {
  MEDIA_STREAM_TYPES,
  MEDIA_STREAM_DELIVERY_TYPE,
};
