const UI_EVENTS = {
  PLAY_TRIGGERED: 'ui-play-triggered',
  PLAY_OVERLAY_TRIGGERED: 'ui-play-overlay-triggered',
  PAUSE_TRIGGERED: 'ui-pause-triggered',
  PROGRESS_CHANGE_TRIGGERED: 'ui-progress-change-triggered',
  VOLUME_CHANGE_TRIGGERED: 'ui-volume-change-triggered',
  MUTE_STATUS_TRIGGERED: 'ui-mute-status-triggered',
  FULLSCREEN_ENTER_TRIGGERED: 'ui-fullscreen-enter-triggered',
  FULLSCREEN_EXIT_TRIGGERED: 'ui-fullscreen-exit-triggered',
  FULLSCREEN_STATUS_CHANGED: 'ui-fullscreen-status-changed',
  MOUSE_ENTER_ON_PLAYER_TRIGGERED: 'ui-mouse-enter-on-player-triggered',
  MOUSE_MOVE_ON_PLAYER_TRIGGERED: 'ui-mouse-move-on-player-triggered',
  MOUSE_LEAVE_ON_PLAYER_TRIGGERED: 'ui-mouse-leave-on-player-triggered',
  CONTROL_BLOCK_HIDE_TRIGGERED: 'ui-control-block-hide-triggered',
  CONTROL_BLOCK_SHOW_TRIGGERED: 'ui-control-block-show-triggered',
  PROGRESS_MANIPULATION_STARTED: 'ui-progress-manipulation-started',
  PROGRESS_MANIPULATION_ENDED: 'ui-progress-manipulation-ended',
  KEYBOARD_KEYDOWN_INTERCEPTED: 'ui-keyboard-keydown-intercepted',
  ENGINE_CONTROL_THROUGH_KEYBOARD_TRIGGERED: 'ui-engine-control-through-keyboard-triggered',
  LOADER_SHOW_TRIGGERED: 'ui-loader-show-triggered',
  LOADER_HIDE_TRIGGERED: 'ui-loader-hide-triggered',
  SHOW_TOP_SHADOW_TRIGGERED: 'ui-show-top-shadow-triggered',
  SHOW_BOTTOM_SHADOW_TRIGGERED: 'ui-show-bottom-shadow-triggered',
  HIDE_TOP_SHADOW_TRIGGERED: 'ui-hide-top-shadow-triggered',
  HIDE_BOTTOM_SHADOW_TRIGGERED: 'ui-hide-bottom-shadow-triggered',
  WATCH_ON_SITE_TRIGGERED: 'ui-watch-on-site-triggered',
  LOADING_COVER_SHOW_TRIGGERED: 'ui-loading-cover-show-triggered',
  LOADING_COVER_HIDE_TRIGGERED: 'ui-loading-cover-hide-triggered',
  PLAY_WITH_SCREEN_CLICK_TRIGGERED: 'ui-play-with-screen-click-triggered',
  PAUSE_WITH_SCREEN_CLICK_TRIGGERED: 'ui-pause-with-screen-click-triggered',
  TOGGLE_PLAYBACK_WITH_KEYBOARD_TRIGGERED: 'ui-toggle-playback-with-keyboard-triggered',
  GO_BACKWARD_WITH_KEYBOARD_TRIGGERED: 'ui-go-backward-with-keyboard-triggered',
  GO_FORWARD_WITH_KEYBOARD_TRIGGERED: 'ui-go-forward-with-keyboard-triggered',
  INCREASE_VOLUME_WITH_KEYBOARD_TRIGGERED: 'ui-increase-volume-with-keyboard-triggered',
  DECREASE_VOLUME_WITH_KEYBOARD_TRIGGERED: 'ui-decrease-volume-with-keyboard-triggered',
  MUTE_SOUND_WITH_KEYBOARD_TRIGGERED: 'ui-mute-sound-with-keyboard-triggered',
  UNMUTE_SOUND_WITH_KEYBOARD_TRIGGERED: 'ui-unmute-sound-with-keyboard-triggered',
  TAB_WITH_KEYBOARD_TRIGGERED: 'ui-tab-with-keyboard-triggered',
  HIDE_MANIPULATION_INDICATOR_TRIGGERED: 'ui-hide-manipulation-indicator-triggered',
  DEBUG_PANEL_TRIGGERED: 'ui-debug-panel-triggered',
  PLAYER_WIDTH_CHANGE_TRIGGERED: 'ui-player-width-change-triggered',
  PLAYER_HEIGHT_CHANGE_TRIGGERED: 'ui-player-height-change-triggered'
};

export default UI_EVENTS;
