docsPath: ./docs
distPath: ./sitedist

mdComponents:
  path: ./docs/md-components/index.js
  externalScripts:
    - https://unpkg.com/playable@2.10.3/dist/statics/playable.bundle.min.js

# https://www.gatsbyjs.org/docs/gatsby-config
config:
  siteMetadata:
    title: playable
  pathPrefix: /playable
  algoliaApiKey: 16e486e2b40c2263303630cc39f2510a
  algoliaIndexName: wix_playable
  githubLink: https://github.com/wix/playable

navigation:
  - path: /
    title: Introduction
  - path: /player-config
    title: Configuration
  - path: /video-source
    title: Video source
  - path: /api
    title: API reference
  - path: /events
    title: Events
  - path: /themes
    title: Themes
  - path: /modules
    title: Modules
  - path: /player-texts
    title: Custom texts
  - path: /adapters
    title: Playback adapters
  - path: /storybook
    title: Storybook
